### ISSUE TITLE
Add Postico to script

### ISSUE THREAD

**Issue by abazlinton** [codeclan/laptop#23] opened 2018-07-09 11:18 UTC
`brew cask install postico` should work...

**Comment by johnmcc** [comment] 2018-07-09 12:14
While this'll be fine for students, as instructors we should be paying for this. (Per the licence.)

**Comment by CraigMorton** [comment] 2018-07-09 13:17
That is an issue. It looks like even for students they want you to pay, as there is a student pricing option. Free version is trial only I think. src= https://sites.fastspring.com/eggerapps/product/postico-selection

Guess we could add `mongodb-compass` to the script though. Since it's in our mongodb lessons now

**Comment by johnmcc** [comment] 2018-07-09 13:54
I'm all for adding a GUI for PostgreSQL by the way, but I've never found a usable, free client that I can recommend.

**Comment by CraigMorton** [comment] 2018-09-13 14:39
I'm going to close this for now as it's not really an issue with the laptop install script. The issue is we need to find a decent, free GUI for Postgres 😂

**Closed by CraigMorton** 2018-09-13 14:39 UTC
